### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by maryamashoori** [trevorfiez/The-Metropolitan-Museum-of-Art-Image-Downloader#4]
Hi, Any idea what's causing this issue?
`python met_download.py --csv=../openaccess-master/MetObjects.csv --out=some_directory --artist="Claude Monet"`

`['Claude Monet']`
`Traceback (most recent call last):`
 ` File "met_download.py", line 158, in <module>`
   ` main(sys.argv[1:])`
 ` File "met_download.py", line 141, in main`
   ` csv_lines = match_lines(met_csv, artists, types, list_file)`
 ` File "met_download.py", line 42, in match_lines`
    `if (check_artists(row[14], artists) and check_types(row[24], types)):`
`IndexError: list index out of range`

**Comment by maryamashoori** [comment]
The CSV file was damaged. It's resolved now. Thanks!
